services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      PORT: 8000
      DATABASE_URL: postgres://postgres:password@db:5432/mydatabase
      API_KEY: ${API_KEY}
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx drizzle-kit migrate && npm run start"
    volumes:
      - ./logs:/app/logs
  db:
    image: postgres:17.2
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d mydatabase -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./logs:/app/logs
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=https://wa.appssimplifica.dev/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  postgres_data:
  grafana-storage:
