CREATE TYPE "public"."user_role" AS ENUM('admin', 'user', 'reader');--> statement-breakpoint
CREATE TABLE "authorization" (
	"id" serial PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"work" text NOT NULL,
	"role" "user_role" DEFAULT 'user' NOT NULL,
	CONSTRAINT "unique_user_on_workspace" UNIQUE("work","userId")
);
--> statement-breakpoint
CREATE TABLE "chat" (
	"pkId" serial PRIMARY KEY NOT NULL,
	"sessionId" varchar(128) NOT NULL,
	"workspaceId" text NOT NULL,
	"archived" boolean,
	"contactPrimaryIdentityKey" "bytea",
	"conversationTimestamp" bigint,
	"createdAt" bigint,
	"createdBy" varchar(128),
	"description" text,
	"disappearingMode" jsonb,
	"displayName" varchar(128),
	"endOfHistoryTransfer" boolean,
	"endOfHistoryTransferType" integer,
	"ephemeralExpiration" integer,
	"ephemeralSettingTimestamp" bigint,
	"id" varchar(128) NOT NULL,
	"isDefaultSubgroup" boolean,
	"isParentGroup" boolean,
	"lastMsgTimestamp" bigint,
	"lidJid" varchar(128),
	"markedAsUnread" boolean,
	"mediaVisibility" integer,
	"messages" jsonb,
	"muteEndTime" bigint,
	"name" varchar(128),
	"newJid" varchar(128),
	"notSpam" boolean,
	"oldJid" varchar(128),
	"pHash" varchar(128),
	"parentGroupId" varchar(128),
	"participant" jsonb,
	"pinned" bigint,
	"pnJid" varchar(128),
	"pnhDuplicateLidThread" boolean,
	"readOnly" boolean,
	"shareOwnPn" boolean,
	"support" boolean,
	"suspended" boolean,
	"tcToken" "bytea",
	"tcTokenSenderTimestamp" bigint,
	"tcTokenTimestamp" bigint,
	"terminated" boolean,
	"unreadCount" integer,
	"unreadMentionCount" integer,
	"wallpaper" jsonb,
	"lastMessageRecvTimestamp" integer,
	"commentsCount" integer
);
--> statement-breakpoint
CREATE TABLE "contacts" (
	"pkId" serial PRIMARY KEY NOT NULL,
	"sessionId" varchar(128) NOT NULL,
	"workspaceId" text NOT NULL,
	"id" varchar(128) NOT NULL,
	"lid" varchar(128),
	"name" varchar(128),
	"notify" varchar(128),
	"verifiedName" varchar(128),
	"imgUrl" varchar(128),
	"status" varchar(128)
);
--> statement-breakpoint
CREATE TABLE "messages" (
	"pkId" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "messages_pkId_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sessionId" varchar(128) NOT NULL,
	"workspaceId" varchar(128) NOT NULL,
	"remoteJid" varchar(128) NOT NULL,
	"id" varchar(128) NOT NULL,
	"agentId" varchar(128),
	"bizPrivacyStatus" integer,
	"broadcast" boolean,
	"clearMedia" boolean,
	"duration" integer,
	"ephemeralDuration" integer,
	"ephemeralOffToOn" boolean,
	"ephemeralOutOfSync" boolean,
	"ephemeralStartTimestamp" bigint,
	"finalLiveLocation" jsonb,
	"futureproofData" "bytea",
	"ignore" boolean,
	"keepInChat" jsonb,
	"key" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"labels" jsonb,
	"mediaCiphertextSha256" "bytea",
	"mediaData" jsonb,
	"message" jsonb,
	"messageC2STimestamp" bigint,
	"messageSecret" "bytea",
	"messageStubParameters" jsonb,
	"messageStubType" integer,
	"messageTimestamp" bigint,
	"multicast" boolean,
	"originalSelfAuthorUserJidString" varchar(128),
	"participant" varchar(128),
	"paymentInfo" jsonb,
	"photoChange" jsonb,
	"pollAdditionalMetadata" jsonb,
	"pollUpdates" jsonb,
	"pushName" varchar(128),
	"quotedPaymentInfo" jsonb,
	"quotedStickerData" jsonb,
	"reactions" jsonb,
	"revokeMessageTimestamp" bigint,
	"starred" boolean,
	"status" integer,
	"statusAlreadyViewed" boolean,
	"statusPsa" jsonb,
	"urlNumber" boolean,
	"urlText" boolean,
	"userReceipt" jsonb,
	"verifiedBizName" varchar(128),
	"eventResponses" jsonb,
	"pinInChat" jsonb,
	"reportingTokenInfo" jsonb
);
--> statement-breakpoint
CREATE TABLE "preferences" (
	"id" serial PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"workspaceId" text NOT NULL,
	"config" jsonb DEFAULT '{"notifications":{"onMessageSend":true},"privacy":{"doNotSyncPreviousChats":false}}'::jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "session_access" (
	"id" serial PRIMARY KEY NOT NULL,
	"sessionId" varchar(128) NOT NULL,
	"workspaceId" text NOT NULL,
	"userId" text NOT NULL,
	"grantedBy" text NOT NULL,
	CONSTRAINT "session_acess_table" UNIQUE("workspaceId","userId","sessionId")
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"pkId" serial PRIMARY KEY NOT NULL,
	"sessionId" varchar(128) NOT NULL,
	"workspaceId" text NOT NULL,
	"id" varchar(255) NOT NULL,
	"data" text NOT NULL,
	"sync" boolean DEFAULT true NOT NULL,
	"createdBy" varchar(128) NOT NULL,
	CONSTRAINT "unique_id_per_session_id" UNIQUE("sessionId","id")
);
--> statement-breakpoint
CREATE TABLE "workspaces" (
	"id" text PRIMARY KEY NOT NULL,
	"name" varchar(500) NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "templates" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(128),
	"workspaceId" text NOT NULL,
	"description" text,
	"message" text,
	"active" boolean DEFAULT true NOT NULL,
	"createdBy" varchar(128) NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"updatedBy" varchar(128) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "authorization" ADD CONSTRAINT "authorization_work_workspaces_id_fk" FOREIGN KEY ("work") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "preferences" ADD CONSTRAINT "preferences_workspaceId_workspaces_id_fk" FOREIGN KEY ("workspaceId") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_access" ADD CONSTRAINT "session_access_workspaceId_workspaces_id_fk" FOREIGN KEY ("workspaceId") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_workspaceId_workspaces_id_fk" FOREIGN KEY ("workspaceId") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "templates" ADD CONSTRAINT "templates_workspaceId_workspaces_id_fk" FOREIGN KEY ("workspaceId") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "unique_chat_id_per_session_id" ON "chat" USING btree ("sessionId","id");--> statement-breakpoint
CREATE INDEX "chat_session_id_index" ON "chat" USING btree ("sessionId");--> statement-breakpoint
CREATE UNIQUE INDEX "unique_contact_id_per_session_id" ON "contacts" USING btree ("sessionId","id");--> statement-breakpoint
CREATE INDEX "contact_session_id_index" ON "contacts" USING btree ("sessionId");--> statement-breakpoint
CREATE UNIQUE INDEX "unique_contact_id_per_session_id_and_workspace_id" ON "messages" USING btree ("sessionId","workspaceId","remoteJid","id");--> statement-breakpoint
CREATE INDEX "session_id_index" ON "sessions" USING btree ("sessionId");